# Generated by Django 4.1.5 on 2023-01-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(upload_to='uploads/logos'),
        ),
    ]
