# Generated by Django 4.1.5 on 2023-01-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='startup',
            name='website',
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_number',
            field=models.CharField(default='Not Available', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='email',
            field=models.EmailField(default='Not Available', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='founder',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_organization', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/mentors')),
                ('area_of_interest', models.ManyToManyField(to='incubation_app.areaofinterest')),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incubation_app.sector'),
        ),
        migrations.AddField(
            model_name='startup',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incubation_app.stage'),
        ),
    ]
