# Generated by Django 4.1.5 on 2023-02-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0004_areaofinterest_sector_stage_remove_startup_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='website',
            field=models.URLField(default='NA'),
        ),
    ]
