# Generated by Django 4.1.5 on 2023-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0005_startup_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
