# Generated by Django 4.1.5 on 2023-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0006_team_bio_team_designation_team_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/gallery')),
            ],
        ),
    ]
