# Generated by Django 4.1.5 on 2023-02-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0007_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Program',
            new_name='program',
        ),
    ]
