# Generated by Django 4.1.5 on 2023-02-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0008_rename_program_gallery_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='mentor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(default='NA', max_length=254),
        ),
        migrations.AddField(
            model_name='mentor',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mentor',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='area_of_interest',
            field=models.ManyToManyField(blank=True, to='incubation_app.areaofinterest'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='current_organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='current_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
