# Generated by Django 4.1.7 on 2023-02-26 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0012_remove_notice_updates_notice_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='update',
            new_name='name',
        ),
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
