# Generated by Django 4.1.7 on 2023-02-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0013_rename_update_notice_name_notice_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='name',
            new_name='update',
        ),
    ]
