# Generated by Django 4.1.7 on 2023-02-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0014_rename_name_notice_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Notices',
        ),
    ]
