# Generated by Django 4.1.7 on 2023-02-26 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0015_rename_notice_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
