# Generated by Django 4.1.7 on 2023-03-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0017_invites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invites',
            new_name='Invite',
        ),
    ]
