# Generated by Django 4.1.7 on 2023-03-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0019_invites_delete_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='uploads/program')),
                ('link', models.URLField(default='NA')),
            ],
        ),
    ]
