# Generated by Django 4.1.7 on 2023-03-03 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incubation_app', '0020_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
